### ISSUE TITLE
Need SECRET_KEY and TMDB_API_KEY to run it?

### ISSUE THREAD

**Issue by hehez** [olivertso/tv-tracker#62]
Need `SECRET_KEY` and `TMDB_API_KEY` to run it?

**Comment by olivertso** [comment]
Yes.

`SECRET_KEY` is required by Django, when developing locally you can just use the value in `.env.example` (more details [here](https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SECRET_KEY)).

And you need `TMDB_API_KEY` so the app can retrieve show data from TMDB api (more details [here](https://developers.themoviedb.org/3/getting-started/introduction)).

**Comment by hehez** [comment]
Let me try later, it threw the `SECRET_KEY ` exception last time.

**Comment by olivertso** [comment]
Did you create the `.env` file? The app gets values from it as environment variables. If not, you can do it with `cp .env.example .env`. Then you only need to register your own `TMDB_API_KEY`.

**Comment by hehez** [comment]
Working
